In [ ]:
import numpy as np
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
y = np.eye(10)
y

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
p = np.diag(x)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 

arange - is used to give random values to the array
linespace - is used to give a range of numbers certain spaces between them(0,1,6) = 0. 0.2 0.4 0.6 0.8 1.0
zeros is used to assign an array zero value
diag - is used to assign the main diagonal the value


In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3 = np.arange(10)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a4 = np.arange(10,20)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a5 = np.arange(10,20,2)
a5

array([10, 12, 14, 16, 18])

In [ ]:
a6 = np.random.randint(10,50,20)
a6

array([44, 31, 42, 10, 22, 37, 14, 26, 46, 22, 26, 11, 33, 12, 18, 48, 39,
       34, 11, 45])

In [ ]:
a2.ndim

2

In [ ]:
a2.shape


(3, 3)

In [ ]:
a.shape

(5,)

In [ ]:
a7 = np.linspace(0,1,6)
a7

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
a8 = np.zeros(3)
a8

array([0., 0., 0.])

In [ ]:
a9 = np.zeros((3,3))
a9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a10 = np.ones(4)
a10

array([1., 1., 1., 1.])

In [ ]:
a11 = np.ones((4,4))
a11

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#generating unit matrix and diaginal matrix
a12 = np.diag([1,1,1,1])
a12

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
a13 = np.diag([1,2,3,4])
a13

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#extracting diagonal matrix
np.diag(a12)

array([1, 1, 1, 1])

In [ ]:
#knowing the data type of the array
a14 = np.arange(10)
a14.dtype

dtype('int64')

In [ ]:
#specifying the type of data type
a15 = np.arange(10,dtype="float64")
a15.dtype

dtype('float64')

In [ ]:
#creating array with complex type
a16 = np.array([[1+2j],[2+4j]])
a16

array([[1.+2.j],
       [2.+4.j]])

In [ ]:
a16.dtype

dtype('complex128')

In [ ]:
#creating boolean array
a17 = np.array([[True,False,True]])
a17

array([[ True, False,  True]])

In [ ]:
a17.dtype

dtype('bool')

In [ ]:
#slicing an array
a18 = np.arange(20)
a18[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a19 = a18[1:9]
a19

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a19[1] = 22
a19

array([ 1, 22,  3,  4,  5,  6,  7,  8])

In [ ]:
a18 #changing the value of an array when you slice it and store in a new variable the update value gets updated also in the main array

array([ 0,  1, 22,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.shares_memory(a18,a19)

True

In [ ]:
a20 = np.arange(10)
a20[5:]=10
a20

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
a21 = a20[0:4].copy() #copy method creates a new memory for the sliced array from the previous one
a21

array([0, 1, 2, 3])

In [ ]:
np.shares_memory(a20,a21)

False

In [ ]:
a20+1

array([ 1,  2,  3,  4,  5, 11, 11, 11, 11, 11])

In [ ]:
a22 = a19+1
a22

array([ 2, 23,  4,  5,  6,  7,  8,  9])

In [ ]:
a23 =([[9,8,7],[6,5,4],[3,2,1]])
a2*a23

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [ ]:
a2.dot(a23)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
np.log(a20)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       2.30258509, 2.30258509, 2.30258509, 2.30258509, 2.30258509])

In [ ]:
np.sin(a20)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111])

In [ ]:
a2.sum(axis=1) # row sum

array([12, 15, 18])

In [ ]:
a2.sum(axis = 0)#column sum

array([12, 15, 18])

In [ ]:
a.min()

1

In [ ]:
a.max()

5

In [ ]:
a.argmin()

0

In [ ]:
a.argmax()

4

In [ ]:
b = np.array([1,2,3,4])
b1 = np.array([1,2,3,4])
np.array_equal(b,b1)

True

In [ ]:
b = np.array([1,2,4,3])
np.array_equiv(b,b1)

False

In [ ]:
b3 = np.tile(np.arange(0,40,10),(4,1))
b3

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
b4 = np.arange(4)
b4

array([0, 1, 2, 3])

In [ ]:
b3 = b3.T
b3

array([[ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [20, 20, 20, 20],
       [30, 30, 30, 30]])

In [ ]:
c = b3+b4
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [ ]:
d = c.ravel() # turning from 2d to 1d
d

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33])

In [ ]:
e = d.reshape((4,4))
e

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [ ]:
f = np.arange(30).reshape(6,5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
x = np.arange(4)
x.resize((8,))
x

array([0, 1, 2, 3, 0, 0, 0, 0])

In [ ]:
y = np.random.randint(10,20,16)
y

array([14, 17, 10, 14, 13, 10, 10, 15, 11, 17, 12, 15, 13, 18, 19, 10])

In [ ]:
np.sort(y)

array([10, 10, 10, 10, 11, 12, 13, 13, 14, 14, 15, 15, 17, 17, 18, 19])

In [ ]:
np.argsort(y)

array([ 2,  5,  6, 15,  8, 10,  4, 12,  0,  3,  7, 11,  1,  9, 13, 14])

In [ ]:
v =y.reshape(4,4)
v

array([[14, 17, 10, 14],
       [13, 10, 10, 15],
       [11, 17, 12, 15],
       [13, 18, 19, 10]])

In [ ]:
np.sort(v, axis=0) # column wise sorting of 2d

array([[11, 10, 10, 10],
       [13, 17, 10, 14],
       [13, 17, 12, 15],
       [14, 18, 19, 15]])

In [ ]:
np.sort(v, axis=1)# row wise sorting of 2d

array([[10, 14, 14, 17],
       [10, 10, 13, 15],
       [11, 12, 15, 17],
       [10, 13, 18, 19]])